ahachulTeam/ahachul_web

src/types/sample.ts
src/utils/sample.ts

test deploy with vercel

---

src/components/common/toggle/styled.ts
src/styles/themes/components/toggle.ts

feat: 토글 컴포넌트 스타일 수정

---

.eslintrc.json
src/assets/icons/ic_arrow_down_min.svg
src/assets/icons/index.ts
src/assets/static/loastFound/filters.ts
src/assets/static/loastFound/index.ts
src/atoms/sample.ts
src/components/common/bottomSheet/BottomSheet.tsx
src/components/common/filter/Filter.tsx
src/components/common/filter/index.ts
src/components/common/filter/styled.ts
src/components/common/index.ts
src/components/domain/index.ts
src/components/domain/lostFound/filterList/FilterList.tsx
src/components/domain/lostFound/filterList/index.ts
src/components/domain/lostFound/filterList/styled.ts
src/components/domain/lostFound/index.ts
src/hooks/index.ts
src/hooks/useArrowKeyTrap.ts
src/hooks/useDisclosure.ts
src/hooks/useFilterList.ts
src/hooks/useKeyTrap.ts
src/hooks/useOnClickOutside.ts
src/hooks/useSample.ts
src/hooks/useScrollDirection.ts
src/utils/navigation.ts
yarn.lock

- #21 
- 필터 컴포넌트 제작
- 접근성 관련 키보드 인터렉션 훅 추가
- 바텀 시트 키보드 인터렉션 적용,
- 바텀 시트 isShow props 예약어 충돌 warning 수정
- 필터 값이 바뀔 때 바텀시트가 자동으로 닫히도록 closedCases props 추가하였습니다.

Feature/#21 필터 컴포넌트

---

pages/_document.tsx

fix: Mixed content 문제 해결

---

apps/web/src/apis/auth.ts
apps/web/src/apis/common.ts
apps/web/src/apis/community.ts
apps/web/src/apis/users.ts

api endpoint에 "/v1" 제거하였습니다.
수정한 baseUrl은 노션에 기입하였습니다 확인 부탁드립니다!
https://www.notion.so/ahhachul/Secrets-37073edf1f2047b687e423dc7e93ad62?pvs=4

[CHORE] api base url 수정

---

packages/ui/src/components/badge/styled.ts
packages/ui/src/components/button/Button.tsx
packages/ui/src/components/button/styled.ts
packages/ui/src/components/checkbox/Checkbox.tsx
packages/ui/src/components/checkbox/styled.ts
packages/ui/src/components/fullHeight/FullHeight.tsx
packages/ui/src/components/search/styled.ts
packages/ui/src/components/tab/styled.ts
packages/ui/src/components/tag/Tag.tsx
packages/ui/src/components/tag/styled.ts
packages/ui/src/components/toggle/styled.ts

아하철 웹 vercel deploy ci  실패하는 문제 해결
- package/ui에서 package/ds theme를 직접 임포트하는 방식으로 변경하였습니다.

[FIX] Vercel ci deploy error

---

apps/web/pages/_app.tsx
apps/web/src/components/layout/header/Header.tsx
apps/web/src/constants/path.ts

#99 
뒤로가기 버튼이 있는 상세 페이지에 유저가 첫 진입했다면, 뒤로가기를 눌렀을 때 
순수 뒤로가기가 아닌, 홈으로 이동시켜주게 했어요
make with sessionStorage

PathStorage

---

apps/web/src/components/domain/main/community/item/Item.tsx
packages/lib/src/hooks/useBoolean.ts
packages/lib/src/types/line.ts
packages/ui/src/components/badge/Badge.stories.tsx
packages/ui/src/components/badge/Badge.tsx
packages/ui/src/components/badge/styled.ts
packages/ui/src/components/checkbox/Checkbox.stories.tsx
packages/ui/src/components/checkbox/Checkbox.tsx
packages/ui/src/components/checkbox/styled.ts

- Badge 컴포넌트 variant props 추가
- Checkbox 컴포넌트 variant props 추가
- checkbox 디자인이 두가지로 나뉘어져 variant props로 분기하였습니다.
- Badge도 상동합니다.

[REFACTORING] UI 공용 컴포넌트 수정

---

apps/web/src/constants/seo.ts
apps/web/src/libs/SEO.tsx
apps/web/src/utils/seo.ts

#108 
og image, url 추가되면 TODO 항목 반영

[FEATURE] SEO 컴포넌트 추가 

---

packages/ui/src/components/button/Button.stories.ts
packages/ui/src/components/button/Button.tsx
packages/ui/src/components/button/styled.ts

#118 
공용 버튼 컴포넌트 ghost, outline 스타일이 빠져있어 추가 하였습니다.

[FEATURE] 공용 버튼 컴포넌트 variant 추가

---

apps/web/src/components/common/dialog/Dialog.tsx
apps/web/src/components/common/dialog/DialogButton.tsx
apps/web/src/components/common/dialog/DialogText.tsx
apps/web/src/components/domain/community/generate/header/CommunityGenerateHeader.tsx
apps/web/src/components/layout/header/Header.tsx

https://github.com/ahachulTeam/ahachul_web/assets/80245801/fe5968aa-c169-4557-8a04-5db2c78fa532

[FEATURE] 다이알로그 공용 컴포넌트 

---

.github/workflows/deploy.yml

[ahhachul.com][FEAT] - add deploy.yml

---

.github/workflows/deploy.yml

feat: update deploy.yml

---

.github/workflows/deploy-web.yml
appspec.yml
deploy.sh
nx.json
packages/esbuild-config/package.json
packages/react/components/button/package.json
packages/react/components/input/package.json
packages/react/components/layout/package.json
packages/react/hooks/button/package.json
packages/react/hooks/input/package.json
packages/react/hooks/toggle/package.json
packages/themes/build.js
packages/themes/package.json
services/next.ahhachul.com/.dockerignore
services/next.ahhachul.com/Dockerfile
services/next.ahhachul.com/Dockerfile.nginx
services/next.ahhachul.com/conf/nginx.conf
services/next.ahhachul.com/next.config.mjs
services/next.ahhachul.com/package.json
services/next.ahhachul.com/src/pages/_app.tsx
services/next.ahhachul.com/tsconfig.json
yarn.lock

chore: next.js ci setup

---

.github/workflows/deploy.yml

chore: update deploy.yml

---

.github/workflows/deploy-web.yml

feat: add codedeploy

---

.github/workflows/deploy-web.yml
services/next.ahhachul.com/src/pages/index.tsx

feat: remove service force updated

---

.github/workflows/deploy-app.yml
.github/workflows/deploy-web.yml

feat: update ci&cd

---

services/next.ahhachul.com/src/hooks/useRouteHistory.ts

- **Figma**:
- **Jira Ticket**:
- **기타 참고 문서**:

feat: test nextjs deploy

---

services/next.ahhachul.com/src/api/auth/index.ts
services/next.ahhachul.com/src/pages/_app.tsx
services/next.ahhachul.com/src/pages/alarm/index.tsx
services/next.ahhachul.com/src/pages/chat/[id]/index.tsx
services/next.ahhachul.com/src/pages/community-editor/index.tsx
services/next.ahhachul.com/src/pages/complaints-ask-train-number/index.tsx
services/next.ahhachul.com/src/pages/complaints-submission/index.tsx
services/next.ahhachul.com/src/pages/lost-editor/index.tsx
services/next.ahhachul.com/src/pages/me/setting/my-ticket.tsx
services/next.ahhachul.com/src/pages/signin/index.tsx

feat: 백엔드 로그인 테스트용

---

.pnp.cjs
packages/react/components/accordion/package.json
packages/react/components/button/package.json
packages/react/components/input/package.json
packages/react/components/layout/package.json
packages/react/components/select/package.json
packages/react/components/toast/package.json
packages/react/hooks/button/package.json
packages/react/hooks/input/package.json
packages/react/hooks/select/package.json
packages/react/hooks/toggle/package.json
packages/react/hooks/utility/package.json
packages/themes/package.json
yarn.lock

fix: windows build

---

.pnp.cjs
package.json
packages/react/components/accordion/package.json
packages/react/components/button/package.json
packages/react/components/input/package.json
packages/react/components/layout/package.json
packages/react/components/select/package.json
packages/react/components/toast/package.json
packages/react/hooks/button/package.json
packages/react/hooks/input/package.json
packages/react/hooks/select/package.json
packages/react/hooks/toggle/package.json
packages/react/hooks/utility/package.json
packages/themes/package.json
services/docs/package.json
services/storybook/package.json
yarn.lock

feat: Next.js 구축 전 typescript 버전 일치 작업

feat: Next.js 구축 전 typescript 버전 일치 작업

---

.github/CODEOWNERS
.github/workflows/ci.yml
package.json

close #232 
ci.yml, codeowners 수정했어요.
기존 ci.yml에서 packages, ahhachul, next.ahhachul 모두 체크했는데
이번에 새롭게 구축한 one-app만을 체크하도록 했어요.
deploy-web.yml 수정은 지금 말고, 구현이 좀 되면 바꾸는 게 좋을 것 같아서 현상태 유지했어요.
이번 pr까지만 main 브렌치에 머지하고,
이후부터는 main브렌치에서 develop 브렌치 만들어서
feature들은 develop에 머지할게요.

refactor!: ci.yml, codeowners 수정

---

services/one-app/src/app/(site)/page.test.tsx
services/one-app/src/app/(site)/page.tsx
services/one-app/tailwind.config.ts

화면 크기에 따라 동적으로 스타일을 입힐 수 있는 config를 설정합니다. 
- tailwind가 app/pages 적용되도록 수정합니다. 
- 화면 크기에 따라 동적으로 스타일을 입힐 수 있는 config를 설정합니다.

chore: apply dynamically config

---

.github/workflows/ci.yml
services/one-app/src/common/constants/env.ts

one-app .env file을 github secrets에 올리고 ci.yml을 수정합니다.
dev, staging, production으로 분기됩니다.

feat: one-app env

---

.github/workflows/ci.yml

프로젝트가 커지면 커질수록 관리되지 않는 타입스크립트 문제들을 액션에서 찾을 수 있도록 합니다.

feat: add typescript compile check

---

services/one-app/next.config.mjs
services/one-app/package.json
services/one-app/tailwind.config.ts
yarn.lock

1. SVG를 바로 import해서 사용 가능하도록 합니다.
2. src전역에서 tailwind 설정 가능하게 합니다.

chore: SVG To direct rendering

---

services/ahhachul.com/src/entities/with-server/model/index.ts
services/ahhachul.com/src/features/articles/model/index.ts
services/ahhachul.com/src/features/articles/ui/ArticleContentParser.css.ts
services/ahhachul.com/src/features/articles/ui/BaseArticleTemplate.css.ts
services/ahhachul.com/src/features/articles/ui/BaseArticleTemplate.tsx
services/ahhachul.com/src/features/subway-lines/lib/generateAccurateSubwayLineId.ts
services/ahhachul.com/src/pages/lost-found/api/get-list.ts
services/ahhachul.com/src/pages/lost-found/data/index.ts
services/ahhachul.com/src/pages/lost-found/ui/_common/LostFoundArticleList/LostFoundArticleList.tsx
services/ahhachul.com/src/pages/lost-found/ui/_common/LostFoundFilters/LostFoundFilters.tsx
services/ahhachul.com/src/shared/lib/utils/array/flattenInfinityList.ts
services/ahhachul.com/src/shared/lib/utils/object/remove-falsy-properties.ts
services/ahhachul.com/src/widgets/articles/ui/ArticleCard.css.ts
services/ahhachul.com/src/widgets/articles/ui/ArticleCard.tsx
services/ahhachul.com/src/widgets/articles/ui/BaseArticleList.tsx
services/ahhachul.com/src/widgets/train-infos/lib/subway-line-hex-colors.ts

유실물 페이지 웹뷰 쪽 코드입니다.
글 작성 쪽은 로그인 기능까지 구현이 가능해서
따로 올리겠습니다.

feat: lost-found (app webview)

---

.husky/pre-commit
.husky/prepare-commit-msg

- **Jira Ticket**: https://github.com/ahachulTeam/ahachul_web/issues/277
- **기타 참고 문서**: GPT
커밋할 때 현재 작업하는 브랜치의 이슈 번호를 추출해서 뒤에 자동을 붙여주도록 했습니다.

chore: 이슈 번호 자동으로 붙도록 설정 추가

---

services/ahhachul.com/src/apis/fetcher.ts
services/ahhachul.com/src/apis/request/token.ts
services/ahhachul.com/src/apis/request/user.ts
services/ahhachul.com/src/components/domain/home/panel/index.ts
services/ahhachul.com/src/components/domain/home/panel/testing/Stations.component.tsx
services/ahhachul.com/src/pages/home/page.tsx
services/ahhachul.com/src/services/user.ts
services/ahhachul.com/src/utils/tokenService.ts

토큰 재발급 절차 관리 및 개선
---
Closes #296

feat: 토큰 재발급 (#296)

---

services/ahhachul.com/src/apis/request/community.ts
services/ahhachul.com/src/apis/request/index.ts
services/ahhachul.com/src/apis/request/lostFound.ts
services/ahhachul.com/src/components/common/filter/drawerFilter/DrawerFilter.component.tsx
services/ahhachul.com/src/components/common/filter/drawerFilter/DrawerFilter.styled.tsx
services/ahhachul.com/src/components/domain/community/index.ts
services/ahhachul.com/src/components/domain/community/searchResults/filters/CommunityFilters.component.tsx
services/ahhachul.com/src/components/domain/community/searchResults/filters/CommunityFilters.styled.tsx
services/ahhachul.com/src/components/domain/community/searchResults/index.ts
services/ahhachul.com/src/components/domain/community/searchResults/searchedList/SearchedList.component.tsx
services/ahhachul.com/src/components/domain/community/searchResults/searchedList/SearchedList.styled.tsx
services/ahhachul.com/src/components/domain/community/searchResults/skeleton/SearchedList.skeleton.styled.tsx
services/ahhachul.com/src/components/domain/community/searchResults/skeleton/SearchedList.skeleton.tsx
services/ahhachul.com/src/components/domain/index.ts
services/ahhachul.com/src/constants/community.ts
services/ahhachul.com/src/constants/index.ts
services/ahhachul.com/src/hooks/domain/community/index.ts
services/ahhachul.com/src/hooks/domain/community/useCommunityFilterStore.ts
services/ahhachul.com/src/pages/community/page.tsx
services/ahhachul.com/src/pages/lostFound/page.tsx
services/ahhachul.com/src/services/community.ts
services/ahhachul.com/src/services/lostFound.ts
services/ahhachul.com/src/types/common.ts
services/ahhachul.com/src/types/community.ts
services/ahhachul.com/src/types/index.ts
services/ahhachul.com/src/types/lostFound.ts

커뮤니티 페이지 글 목록 조회
---
Closes #297

feat: 커뮤니티 페이지 글 목록 조회

---

packages/utils/src/date.ts
services/ahhachul.com/src/apis/request/community.ts
services/ahhachul.com/src/apis/request/lostFound.ts
services/ahhachul.com/src/components/common/list/listItem/ListItem.component.tsx
services/ahhachul.com/src/components/domain/community/index.ts
services/ahhachul.com/src/components/domain/community/postDetail/categoryBadge/CommunityCategoryBadge.component.tsx
services/ahhachul.com/src/components/domain/community/postDetail/categoryBadge/CommunityCategoryBadge.styled.tsx
services/ahhachul.com/src/components/domain/community/postDetail/commentList/CommunityCommentList.component.tsx
services/ahhachul.com/src/components/domain/community/postDetail/commentList/CommunityCommentList.styled.tsx
services/ahhachul.com/src/components/domain/community/postDetail/error/CommunityErrorPage.component.tsx
services/ahhachul.com/src/components/domain/community/postDetail/error/CommunityErrorPage.styled.tsx
services/ahhachul.com/src/components/domain/community/postDetail/headerActions/CommunityHeaderActions.component.tsx
services/ahhachul.com/src/components/domain/community/postDetail/headerActions/CommunityHeaderActions.styled.tsx
services/ahhachul.com/src/components/domain/community/postDetail/index.ts
services/ahhachul.com/src/components/domain/community/postDetail/skeleton/CommunityDetail.skeleton.styled.tsx
services/ahhachul.com/src/components/domain/community/postDetail/skeleton/CommunityDetail.skeleton.tsx
services/ahhachul.com/src/components/domain/community/postDetail/template/CommunityDetail.component.tsx
services/ahhachul.com/src/components/domain/community/postDetail/template/CommunityDetail.styled.tsx
services/ahhachul.com/src/components/domain/lostFound/postDetail/lost112InfoTable/Lost112InfoTable.component.tsx
services/ahhachul.com/src/components/domain/lostFound/postDetail/lostFoundBadge/LostFoundBadge.component.tsx
services/ahhachul.com/src/components/domain/lostFound/postDetail/lostFoundBadge/LostFoundBadge.styled.tsx
services/ahhachul.com/src/components/domain/lostFound/postDetail/recommendPostList/listItem/ListItem.component.tsx
services/ahhachul.com/src/components/domain/lostFound/postDetail/template/LostFoundDetail.component.tsx
services/ahhachul.com/src/hooks/domain/my/useUser.ts
services/ahhachul.com/src/pages/community/[id]/page.tsx
services/ahhachul.com/src/services/community.ts
services/ahhachul.com/src/services/lostFound.ts
services/ahhachul.com/src/types/common.ts
services/ahhachul.com/src/types/community.ts

community detail page (#300)
---
Closes #300

feat: community detail page (#300)

---

packages/utils/src/date.ts
services/ahhachul.com/src/apis/request/community.ts
services/ahhachul.com/src/components/common/form/organisms/image/ImageUpload.component.tsx
services/ahhachul.com/src/components/domain/community/edit/index.ts
services/ahhachul.com/src/components/domain/community/edit/template/EditCommunity.component.tsx
services/ahhachul.com/src/components/domain/community/edit/template/EditCommunity.styled.tsx
services/ahhachul.com/src/components/domain/community/index.ts
services/ahhachul.com/src/components/domain/home/panel/testing/Stations.component.tsx
services/ahhachul.com/src/constants/community.ts
services/ahhachul.com/src/hooks/domain/community/index.ts
services/ahhachul.com/src/hooks/domain/community/useCommunityForm.ts
services/ahhachul.com/src/hooks/domain/community/useEditCommunityForm.ts
services/ahhachul.com/src/pages/community/[id]/edit.tsx
services/ahhachul.com/src/pages/community/new.tsx
services/ahhachul.com/src/pages/lostFound/new.tsx
services/ahhachul.com/src/services/community.ts
services/ahhachul.com/src/services/lostFound.ts
services/ahhachul.com/src/types/community.ts
services/ahhachul.com/src/utils/form.ts

커뮤니티 게시글 생성 및 수정 (#302)
---
Closes #302

feat: 커뮤니티 게시글 생성 및 수정 (#302)
